version: "2"

linters:
  default: standard
  enable:
    # Checks that all code identifiers does not have non-ASCII symbols in the name.
    - asciicheck
    # Checks for dangerous unicode character sequences.
    - bidichk
    # A linter detects places where loop variables are copied.
    - copyloopvar
    # Checks function and package cyclomatic complexity.
    - cyclop
    # Check declaration order and count of types, constants, variables and functions.
    - decorder
    # Detects duplicate fragments of code.
    - dupl
    # Embedded types should be at the top of the field list of a struct,
    # and there must be an empty line separating embedded fields from regular fields.
    - embeddedstructfieldcheck
    # Check errors handling expressions.
    - err113
    # Errcheck is a program for checking for unchecked errors in Go code. These unchecked errors can be critical bugs in some cases.
    - errcheck
    # Checks types passed to the json encoding functions.
    # Reports unsupported types and reports occurrences where the check for the returned error can be omitted.
    - errchkjson
    # Checks that sentinel errors are prefixed with the Err and error types are suffixed with the Error.
    - errname
    # Find code that can cause problems with the error wrapping scheme introduced in Go 1.13.
    - errorlint
    # Detects functions from golang.org/x/exp/ that can be replaced by std functions.
    - exptostd
    # Checks the order of functions, methods, and constructors.
    - funcorder
    # Finds repeated strings that could be replaced by a constant.
    - goconst
    # Provides diagnostics that check for bugs, performance and style issues.
    # Extensible without recompilation through dynamic rules.
    # Dynamic rules are written declaratively with AST patterns, filters, report message and optional suggestion.
    - gocritic
    # Checks Golang's documentation practice (godoc).
    - godoclint
    # Check if comments end in a period.
    - godot
    # Detects usage of FIXME, TODO and other keywords inside comments.
    - godox
    # Inspects source code for security problems.
    - gosec
    # Vet examines Go source code and reports suspicious constructs. It is roughly the same as 'go vet' and uses its passes.
    - govet
    # Detects when assignments to existing variables are not used.
    - ineffassign
    # Reports long lines.
    - lll
    # Reports deeply nested if statements.
    - nestif
    # Find the code that returns nil even if it checks that the error is not nil.
    - nilerr
    # Checks for a new line before return and branch statements to increase code clarity.
    - nlreturn
    # Checks that fmt.Sprintf can be replaced with a faster alternative.
    - perfsprint
    # Find slice declarations that could potentially be pre-allocated.
    - prealloc
    # Checks that package variables are not reassigned.
    - reassign
    # Checks for receiver type consistency.
    - recvcheck
    # It's the set of rules from staticcheck.
    - staticcheck
    # Linter checks if examples are testable (have an expected output).
    - testableexamples
    # Reports unused function parameters.
    - unparam
    # Checks Go code for unused constants, variables, functions and types.
    - unused
  settings:
    staticcheck:
      checks:
        - all
    decorder:
      # Required order of `type`, `const`, `var` and `func` declarations inside a file.
      # Default: types before constants before variables before functions.
      dec-order:
        - const
        - var
        - type
        - func
      disable-dec-order-check: false
    iface:
      # List of analyzers.
      enable:
        - identical # Identifies interfaces in the same package that have identical method sets.
        - unused # Identifies interfaces that are not used anywhere in the same package where the interface is defined.
        - opaque # Identifies functions that return interfaces, but the actual returned value is always a single concrete implementation.
        - unexported # Identifies interfaces that are not exported but are used in exported functions or methods.
formatters:
  enable:
    - gofmt
    - goimports