input {
  file {
    path => "/var/log/bot/*.log"
    mode => "tail"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb_bot"
    codec => json
  }
}

filter {
  if [ts] {
    date {
      match => ["ts", "ISO8601"]
      target => "@timestamp"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "bot-logs-%{+YYYY.MM.dd}"
    ilm_enabled => false
  }
}
